scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 2s
    static_configs:
      - targets: ["otel-collector:8888"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"
