auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

schema_config:
  configs:
    # New TSDB schema below
    - from: "2023-01-05" # <---- A date in the future
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb

storage_config:
  filesystem:
    directory: /tmp/loki/
  # New tsdb-shipper configuration
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    shared_store: filesystem

# query_scheduler:
#   # the TSDB index dispatches many more, but each individually smaller, requests.
#   # We increase the pending request queue sizes to compensate.
#   max_outstanding_requests_per_tenant: 32768

# querier:
#   # Each `querier` component process runs a number of parallel workers to process queries simultaneously.
#   # You may want to adjust this up or down depending on your resource usage
#   # (more available cpu and memory can tolerate higher values and vice versa),
#   # but we find the most success running at around `16` with tsdb
#   max_concurrent: 16

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
#   compaction_interval: 10m
#   retention_enabled: true
#   retention_delete_delay: 2h
#   retention_delete_worker_count: 150

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
#     final_sleep: 0s

#   chunk_idle_period: 1h       # Any chunk not receiving new logs for 1 hour will be flushed
#   chunk_retain_period: 30s    # Chunks will be retained for at least 30 seconds before being flushed
#   max_transfer_retries: 0     # Ingester will not retry any transfers on shutdown or after a crash

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  enable_api: true
