auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

schema_config:
  configs:
    - from: "2023-01-05"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb

storage_config:
  filesystem:
    directory: /tmp/loki/
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    shared_store: filesystem

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  enable_api: true
